# Error Reference data_logger.py
- `-2`  Python side interrupt
- `-1`  exited the program successfully
- `0`   data reveived successfully
- `1`   conversion to utf-8 failed
- `2`   conversion to list of length 3 or more failed
- `3`   conversion of list elements to float failed
- `4`   received message was empty